// Traduceri pentru pagina "Echipa Angajați" (RO / EN / FR / NL)
const LABELS = {
  ro: {
    title: 'Echipa Angajați',
    subtitle: 'Gestionează personalul care are acces să scaneze la această locație.',
    exportData: 'Exportă Date',
    addEmployee: 'Adaugă Angajat',
    loading: 'Se încarcă angajații...',
    tabActive: 'Activi',
    tabArchive: 'Arhivă',
    searchPh: 'Caută după nume, cod sau CNP...',
    searchArchivePh: 'Caută în arhivă...',
    results: 'rez.',
    selOne: 'angajat selectat',
    selMany: 'angajați selectați',
    helpArchived: 'Poți restaura angajații selectați în lista activă.',
    helpActive: 'Poți schimba funcția/locația în masă sau poți arhiva înregistrările selectate.',
    exportBtn: 'Exportă',
    restore: 'Restaurează',
    editData: 'Editează Date',
    bulkEdit: 'Modifică în Masă',
    archive: 'Arhivează',
    cancel: 'Anulează',
    pageSelPre: 'Sunt selectați toți cei',
    pageSelPost: 'angajați de pe această pagină.',
    selectAllFiltered: (n) => `Selectează toți cei ${n} angajați din lista filtrată`,
    tipDeselectAll: 'Deselectează toate',
    tipSelectAllPage: 'Selectează toate de pe pagină',
    thNr: 'Nr.',
    thEmployee: 'Angajat',
    thJob: 'Funcție',
    thBirth: 'Data Nașterii / Vârstă',
    thPin: 'PIN / Acces',
    thActions: 'Acțiuni',
    noRecords: 'Nu s-au găsit înregistrări.',
    addFirst: 'Adaugă primul angajat',
    pinResetBadge: 'Resetare PIN cerută',
    unknownLoc: 'Punct lucru necunoscut',
    years: (n) => `${n} ani`,
    tipRestoreArchive: 'Restaurează din Arhivă',
    tipResetPin: 'Resetează PIN',
    tipPrint: 'Printează Legitimație (QR)',
    tipEdit: 'Editează Angajat',
    tipArchive: 'Arhivează Angajat',
    show: 'Afișează',
    all: 'Toți',
    totalRecords: 'Total înregistrări:',
    pageOf: (p, n) => `Pagina ${p} din ${n}`,
    archiveTitle: 'Arhivare Angajat',
    archiveMsg: (name) => `Ești sigur că vrei să arhivezi angajatul ${name}? Acesta va fi mutat în arhivă, nu va mai putea efectua pontaje, iar codul său rămâne rezervat pentru a preveni orice conflict.`,
    restoreTitle: 'Restaurare Angajat',
    restoreMsg: (name) => `Sigur dorești să reactivezi angajatul ${name} din arhivă? Acesta va putea efectua din nou pontajul folosind același cod.`,
    bulkArchiveTitle: 'Arhivare în Masă',
    bulkArchiveMsg: (n) => `Ești sigur că vrei să arhivezi cei ${n} angajați selectați? Aceștia vor fi mutați în arhivă, iar codurile lor vor rămâne rezervate.`,
    archiving: 'Se arhivează...',
    archiveN: (n) => `Arhivează (${n})`,
    bulkRestoreTitle: 'Restaurare în Masă',
    bulkRestoreMsg: (n) => `Sigur dorești să reactivezi cei ${n} angajați selectați din arhivă?`,
    restoring: 'Se restaurează...',
    restoreN: (n) => `Restaurează (${n})`,
    bulkModalTitle: 'Modificare în Masă Angajați',
    bulkSubPre: 'Aplică modificări simultane pentru cei',
    bulkSubPost: 'angajați selectați',
    bulkChangeJob: 'Modifică Funcția (Rolul)',
    bulkNoJob: '-- Fără funcție atribuită --',
    bulkChangeLoc: 'Modifică Punctul de Lucru (Locația)',
    bulkNoLoc: '-- Fără punct de lucru atribuit --',
    applying: 'Se aplică...',
    applyTo: (n) => `Aplică la ${n} ${n === 1 ? 'Angajat' : 'Angajați'}`,
    resetPinTitle: 'Resetare PIN',
    resetPinMsgShort: 'Ești sigur că vrei să resetezi PIN-ul acestui angajat?',
    resetPinMsgLong: 'Sigur doriți să resetați PIN-ul pentru acest angajat? Acesta va primi un PIN nou.',
    resetBtn: 'Resetează',
    pinResetDone: 'PIN Resetat',
    pinResetOk: (pin) => `PIN-ul a fost resetat cu succes!\nNoul PIN este: ${pin}`,
    success: 'Succes',
    close: 'Închide',
    defaultJob: 'Angajat',
    qrScanNote: 'Scanarea se face de către tableta kiosk-ului sau de pe alt dispozitiv.',
    qrSendLink: 'Trimiteți link-ul portalului către angajat pentru a se autentifica și a-și accesa legitimația digitală.',
    copied: 'Copiat!',
    copyLink: 'Copiază Link Portal',
    modalEdit: 'Editează Angajat',
    modalAdd: 'Adaugă Angajat Nou',
    modalEditSub: 'Actualizează datele angajatului',
    modalAddSub: 'Profil pontaj și date identificare',
    tab1: '1. Date & Contact',
    tab2: '2. Funcție & Contract',
    increaseSeats: 'Mărește Locurile Abonamentului (Prorata)',
    ocrBusy: 'Scanare automată în curs...',
    ocrIdle: 'Apasă aici pentru a scana un Buletin (C.I.)',
    ocrHint: 'Sistemul va tăia și extrage automat poza angajatului.',
    avatarAlt: 'Avatar extras',
    avatarCaption: 'Poză extrasă automat',
    lastName: 'Nume *',
    firstName: 'Prenume *',
    cnp: 'CNP *',
    birthDate: 'Data Nașterii',
    extractedFrom: 'Extras din CNP / C.I.',
    idSeries: 'Serie și Număr C.I.',
    address: 'Adresă (din C.I.)',
    phone: 'Telefon',
    email: 'Email',
    jobLabel: 'Meserie (Funcția din Firmă)',
    chooseJob: '-- Alege o meserie --',
    newBtn: 'Nou',
    newJobPh: 'Nume meserie nouă...',
    pinLabel: 'PIN Acces (Din CNP)',
    pinHelp: 'Acest PIN (parolă scurtă) este extras din ultimele 4 cifre ale CNP-ului. Angajatul îl va folosi exclusiv pentru a scana codul QR pe tabletă la intrare/ieșire.',
    workSite: 'Punct de Lucru',
    noFixedSite: '-- Fără punct de lucru fix --',
    hireDate: 'Data Angajării',
    salary: 'Salariu',
    salaryPh: 'Ex: 4000 RON',
    contractNotes: 'Notițe Contract',
    notesPh: 'Detalii adiționale...',
    saveEmployee: 'Salvează Angajatul',
    errOcr: 'Eroare la citirea buletinului. Completează manual.',
    errSave: 'Eroare la salvare. Verificați datele.',
    errBulkArchive: 'Eroare la arhivarea în masă a angajaților.',
    errBulkRestore: 'Eroare la restaurarea în masă a angajaților.',
    errBulkUpdate: 'Eroare la actualizarea în masă.',
    errBulkPick: 'Bifează cel puțin un câmp de modificat (Funcție sau Punct de Lucru).',
    errConn: 'Eroare la conexiunea cu serverul.',
    errConn2: 'Eroare de conexiune cu serverul.',
    alertNoEmp: 'Nu există angajați de exportat.',
    alertNoCol: 'Vă rugăm să selectați cel puțin o coloană pentru export.',
    exportModalTitle: 'Export Date Angajați',
    exportModalSub: 'Selectează coloanele și formatul dorit pentru descărcare.',
    exportInclude: 'Angajați incluși în export:',
    onlySelected: (n) => `Doar cei ${n} selectați`,
    allEmployees: (n) => `Toți angajații (${n})`,
    colsHeader: (n) => `Coloane de exportat (${n} selectate)`,
    onlyNameCodePin: 'Doar Nume, Cod & PIN',
    selAll: 'Selectează tot',
    deselect: 'Deselectează',
    formatLabel: 'Format fișier:',
    download: (fmt) => `Descarcă ${fmt}`,
    sheetName: 'Angajați',
    statusActive: 'Activ',
    statusArchived: 'Arhivat',
    cols: {
      full_name: 'Nume și Prenume',
      employee_code: 'Cod Angajat',
      pin_code: 'Cod PIN Pontaj',
      job_title: 'Funcție / Rol COR',
      cnp: 'CNP',
      birth_date: 'Data Nașterii',
      phone: 'Număr Telefon',
      email: 'Email',
      address: 'Adresă Domiciliu',
      location_name: 'Punct de Lucru / Locație',
      work_schedule: 'Normă Lucru',
      salary: 'Salariu',
      contract_start_date: 'Data Început Contract',
      id_card_series: 'Serie & Număr CI',
      status: 'Status (Activ / Arhivat)'
    }
  },
  en: {
    title: 'Employee Team',
    subtitle: 'Manage the staff who have access to scan at this location.',
    exportData: 'Export Data',
    addEmployee: 'Add Employee',
    loading: 'Loading employees...',
    tabActive: 'Active',
    tabArchive: 'Archive',
    searchPh: 'Search by name, code or ID number...',
    searchArchivePh: 'Search the archive...',
    results: 'res.',
    selOne: 'employee selected',
    selMany: 'employees selected',
    helpArchived: 'You can restore the selected employees to the active list.',
    helpActive: 'You can change the job/location in bulk or archive the selected records.',
    exportBtn: 'Export',
    restore: 'Restore',
    editData: 'Edit Data',
    bulkEdit: 'Bulk Edit',
    archive: 'Archive',
    cancel: 'Cancel',
    pageSelPre: 'All',
    pageSelPost: 'employees on this page are selected.',
    selectAllFiltered: (n) => `Select all ${n} employees in the filtered list`,
    tipDeselectAll: 'Deselect all',
    tipSelectAllPage: 'Select all on this page',
    thNr: 'No.',
    thEmployee: 'Employee',
    thJob: 'Job Title',
    thBirth: 'Date of Birth / Age',
    thPin: 'PIN / Access',
    thActions: 'Actions',
    noRecords: 'No records found.',
    addFirst: 'Add the first employee',
    pinResetBadge: 'PIN reset requested',
    unknownLoc: 'Unknown work site',
    years: (n) => `${n} years`,
    tipRestoreArchive: 'Restore from Archive',
    tipResetPin: 'Reset PIN',
    tipPrint: 'Print Badge (QR)',
    tipEdit: 'Edit Employee',
    tipArchive: 'Archive Employee',
    show: 'Show',
    all: 'All',
    totalRecords: 'Total records:',
    pageOf: (p, n) => `Page ${p} of ${n}`,
    archiveTitle: 'Archive Employee',
    archiveMsg: (name) => `Are you sure you want to archive ${name}? They will be moved to the archive and will no longer be able to clock in, and their code stays reserved to prevent any conflict.`,
    restoreTitle: 'Restore Employee',
    restoreMsg: (name) => `Are you sure you want to reactivate ${name} from the archive? They will be able to clock in again using the same code.`,
    bulkArchiveTitle: 'Bulk Archive',
    bulkArchiveMsg: (n) => `Are you sure you want to archive the ${n} selected employees? They will be moved to the archive and their codes will stay reserved.`,
    archiving: 'Archiving...',
    archiveN: (n) => `Archive (${n})`,
    bulkRestoreTitle: 'Bulk Restore',
    bulkRestoreMsg: (n) => `Are you sure you want to reactivate the ${n} selected employees from the archive?`,
    restoring: 'Restoring...',
    restoreN: (n) => `Restore (${n})`,
    bulkModalTitle: 'Bulk Edit Employees',
    bulkSubPre: 'Apply changes at once to the',
    bulkSubPost: 'selected employees',
    bulkChangeJob: 'Change Job Title (Role)',
    bulkNoJob: '-- No job assigned --',
    bulkChangeLoc: 'Change Work Site (Location)',
    bulkNoLoc: '-- No work site assigned --',
    applying: 'Applying...',
    applyTo: (n) => `Apply to ${n} ${n === 1 ? 'Employee' : 'Employees'}`,
    resetPinTitle: 'Reset PIN',
    resetPinMsgShort: 'Are you sure you want to reset this employee\'s PIN?',
    resetPinMsgLong: 'Are you sure you want to reset the PIN for this employee? They will receive a new PIN.',
    resetBtn: 'Reset',
    pinResetDone: 'PIN Reset',
    pinResetOk: (pin) => `The PIN was reset successfully!\nThe new PIN is: ${pin}`,
    success: 'Success',
    close: 'Close',
    defaultJob: 'Employee',
    qrScanNote: 'Scanning is done by the kiosk tablet or another device.',
    qrSendLink: 'Send the portal link to the employee so they can sign in and access their digital badge.',
    copied: 'Copied!',
    copyLink: 'Copy Portal Link',
    modalEdit: 'Edit Employee',
    modalAdd: 'Add New Employee',
    modalEditSub: 'Update the employee data',
    modalAddSub: 'Clock-in profile and identification data',
    tab1: '1. Details & Contact',
    tab2: '2. Job & Contract',
    increaseSeats: 'Increase Subscription Seats (Prorata)',
    ocrBusy: 'Automatic scan in progress...',
    ocrIdle: 'Click here to scan an ID card',
    ocrHint: 'The system will automatically crop and extract the employee photo.',
    avatarAlt: 'Extracted avatar',
    avatarCaption: 'Photo extracted automatically',
    lastName: 'Last name *',
    firstName: 'First name *',
    cnp: 'ID number (CNP) *',
    birthDate: 'Date of Birth',
    extractedFrom: 'Extracted from CNP / ID card',
    idSeries: 'ID Card Series and Number',
    address: 'Address (from ID card)',
    phone: 'Phone',
    email: 'Email',
    jobLabel: 'Job Title (Role in the Company)',
    chooseJob: '-- Choose a job --',
    newBtn: 'New',
    newJobPh: 'New job name...',
    pinLabel: 'Access PIN (From CNP)',
    pinHelp: 'This PIN (short password) is taken from the last 4 digits of the CNP. The employee uses it only to scan the QR code on the tablet when checking in/out.',
    workSite: 'Work Site',
    noFixedSite: '-- No fixed work site --',
    hireDate: 'Hire Date',
    salary: 'Salary',
    salaryPh: 'E.g.: 4000 RON',
    contractNotes: 'Contract Notes',
    notesPh: 'Additional details...',
    saveEmployee: 'Save Employee',
    errOcr: 'Error reading the ID card. Fill in manually.',
    errSave: 'Error while saving. Please check the data.',
    errBulkArchive: 'Error while archiving the employees in bulk.',
    errBulkRestore: 'Error while restoring the employees in bulk.',
    errBulkUpdate: 'Error during the bulk update.',
    errBulkPick: 'Tick at least one field to change (Job Title or Work Site).',
    errConn: 'Error connecting to the server.',
    errConn2: 'Connection error with the server.',
    alertNoEmp: 'There are no employees to export.',
    alertNoCol: 'Please select at least one column to export.',
    exportModalTitle: 'Export Employee Data',
    exportModalSub: 'Select the columns and the format you want to download.',
    exportInclude: 'Employees included in the export:',
    onlySelected: (n) => `Only the ${n} selected`,
    allEmployees: (n) => `All employees (${n})`,
    colsHeader: (n) => `Columns to export (${n} selected)`,
    onlyNameCodePin: 'Only Name, Code & PIN',
    selAll: 'Select all',
    deselect: 'Deselect',
    formatLabel: 'File format:',
    download: (fmt) => `Download ${fmt}`,
    sheetName: 'Employees',
    statusActive: 'Active',
    statusArchived: 'Archived',
    cols: {
      full_name: 'Full Name',
      employee_code: 'Employee Code',
      pin_code: 'Clock-in PIN',
      job_title: 'Job Title / Role',
      cnp: 'CNP',
      birth_date: 'Date of Birth',
      phone: 'Phone Number',
      email: 'Email',
      address: 'Home Address',
      location_name: 'Work Site / Location',
      work_schedule: 'Work Schedule',
      salary: 'Salary',
      contract_start_date: 'Contract Start Date',
      id_card_series: 'ID Card Series & Number',
      status: 'Status (Active / Archived)'
    }
  },
  fr: {
    title: "Équipe des employés",
    subtitle: "Gérez le personnel qui a accès au pointage sur ce site.",
    exportData: 'Exporter les données',
    addEmployee: 'Ajouter un employé',
    loading: 'Chargement des employés...',
    tabActive: 'Actifs',
    tabArchive: 'Archives',
    searchPh: 'Rechercher par nom, code ou CNP...',
    searchArchivePh: "Rechercher dans l'archive...",
    results: 'rés.',
    selOne: 'employé sélectionné',
    selMany: 'employés sélectionnés',
    helpArchived: 'Vous pouvez restaurer les employés sélectionnés dans la liste active.',
    helpActive: "Vous pouvez modifier le poste/le lieu en masse ou archiver les enregistrements sélectionnés.",
    exportBtn: 'Exporter',
    restore: 'Restaurer',
    editData: 'Modifier les données',
    bulkEdit: 'Modification en masse',
    archive: 'Archiver',
    cancel: 'Annuler',
    pageSelPre: 'Les',
    pageSelPost: 'employés de cette page sont tous sélectionnés.',
    selectAllFiltered: (n) => `Sélectionner les ${n} employés de la liste filtrée`,
    tipDeselectAll: 'Tout désélectionner',
    tipSelectAllPage: 'Tout sélectionner sur la page',
    thNr: 'N°',
    thEmployee: 'Employé',
    thJob: 'Poste',
    thBirth: 'Date de naissance / Âge',
    thPin: 'PIN / Accès',
    thActions: 'Actions',
    noRecords: 'Aucun enregistrement trouvé.',
    addFirst: 'Ajouter le premier employé',
    pinResetBadge: 'Réinitialisation du PIN demandée',
    unknownLoc: 'Lieu de travail inconnu',
    years: (n) => `${n} ans`,
    tipRestoreArchive: "Restaurer depuis l'archive",
    tipResetPin: 'Réinitialiser le PIN',
    tipPrint: 'Imprimer le badge (QR)',
    tipEdit: "Modifier l'employé",
    tipArchive: "Archiver l'employé",
    show: 'Afficher',
    all: 'Tous',
    totalRecords: "Total d'enregistrements :",
    pageOf: (p, n) => `Page ${p} sur ${n}`,
    archiveTitle: "Archiver l'employé",
    archiveMsg: (name) => `Voulez-vous vraiment archiver ${name} ? Il sera déplacé dans l'archive, ne pourra plus pointer, et son code reste réservé pour éviter tout conflit.`,
    restoreTitle: "Restaurer l'employé",
    restoreMsg: (name) => `Voulez-vous vraiment réactiver ${name} depuis l'archive ? Il pourra de nouveau pointer avec le même code.`,
    bulkArchiveTitle: 'Archivage en masse',
    bulkArchiveMsg: (n) => `Voulez-vous vraiment archiver les ${n} employés sélectionnés ? Ils seront déplacés dans l'archive et leurs codes resteront réservés.`,
    archiving: 'Archivage...',
    archiveN: (n) => `Archiver (${n})`,
    bulkRestoreTitle: 'Restauration en masse',
    bulkRestoreMsg: (n) => `Voulez-vous vraiment réactiver les ${n} employés sélectionnés depuis l'archive ?`,
    restoring: 'Restauration...',
    restoreN: (n) => `Restaurer (${n})`,
    bulkModalTitle: 'Modification en masse des employés',
    bulkSubPre: 'Appliquer des modifications simultanées aux',
    bulkSubPost: 'employés sélectionnés',
    bulkChangeJob: 'Modifier le poste (rôle)',
    bulkNoJob: '-- Aucun poste attribué --',
    bulkChangeLoc: 'Modifier le lieu de travail',
    bulkNoLoc: '-- Aucun lieu de travail attribué --',
    applying: 'Application...',
    applyTo: (n) => `Appliquer à ${n} ${n === 1 ? 'employé' : 'employés'}`,
    resetPinTitle: 'Réinitialisation du PIN',
    resetPinMsgShort: 'Voulez-vous vraiment réinitialiser le PIN de cet employé ?',
    resetPinMsgLong: 'Voulez-vous vraiment réinitialiser le PIN de cet employé ? Il recevra un nouveau PIN.',
    resetBtn: 'Réinitialiser',
    pinResetDone: 'PIN réinitialisé',
    pinResetOk: (pin) => `Le PIN a été réinitialisé avec succès !\nLe nouveau PIN est : ${pin}`,
    success: 'Succès',
    close: 'Fermer',
    defaultJob: 'Employé',
    qrScanNote: "Le scan se fait avec la tablette du kiosque ou un autre appareil.",
    qrSendLink: "Envoyez le lien du portail à l'employé pour qu'il se connecte et accède à son badge numérique.",
    copied: 'Copié !',
    copyLink: 'Copier le lien du portail',
    modalEdit: "Modifier l'employé",
    modalAdd: 'Ajouter un nouvel employé',
    modalEditSub: "Mettre à jour les données de l'employé",
    modalAddSub: "Profil de pointage et données d'identification",
    tab1: '1. Données & Contact',
    tab2: '2. Poste & Contrat',
    increaseSeats: "Augmenter les places de l'abonnement (prorata)",
    ocrBusy: 'Scan automatique en cours...',
    ocrIdle: "Cliquez ici pour scanner une carte d'identité",
    ocrHint: "Le système découpera et extraira automatiquement la photo de l'employé.",
    avatarAlt: 'Avatar extrait',
    avatarCaption: 'Photo extraite automatiquement',
    lastName: 'Nom *',
    firstName: 'Prénom *',
    cnp: 'CNP *',
    birthDate: 'Date de naissance',
    extractedFrom: "Extrait du CNP / de la carte d'identité",
    idSeries: "Série et numéro de la carte d'identité",
    address: "Adresse (de la carte d'identité)",
    phone: 'Téléphone',
    email: 'E-mail',
    jobLabel: "Métier (poste dans l'entreprise)",
    chooseJob: '-- Choisir un métier --',
    newBtn: 'Nouveau',
    newJobPh: 'Nom du nouveau métier...',
    pinLabel: "PIN d'accès (issu du CNP)",
    pinHelp: "Ce PIN (mot de passe court) est tiré des 4 derniers chiffres du CNP. L'employé l'utilise uniquement pour scanner le code QR sur la tablette à l'entrée/sortie.",
    workSite: 'Lieu de travail',
    noFixedSite: '-- Aucun lieu de travail fixe --',
    hireDate: "Date d'embauche",
    salary: 'Salaire',
    salaryPh: 'Ex : 4000 RON',
    contractNotes: 'Notes du contrat',
    notesPh: 'Détails supplémentaires...',
    saveEmployee: "Enregistrer l'employé",
    errOcr: "Erreur de lecture de la carte d'identité. Remplissez manuellement.",
    errSave: "Erreur lors de l'enregistrement. Vérifiez les données.",
    errBulkArchive: "Erreur lors de l'archivage en masse des employés.",
    errBulkRestore: 'Erreur lors de la restauration en masse des employés.',
    errBulkUpdate: 'Erreur lors de la mise à jour en masse.',
    errBulkPick: 'Cochez au moins un champ à modifier (poste ou lieu de travail).',
    errConn: 'Erreur de connexion au serveur.',
    errConn2: 'Erreur de connexion avec le serveur.',
    alertNoEmp: "Il n'y a aucun employé à exporter.",
    alertNoCol: 'Veuillez sélectionner au moins une colonne à exporter.',
    exportModalTitle: 'Exporter les données des employés',
    exportModalSub: 'Sélectionnez les colonnes et le format souhaités pour le téléchargement.',
    exportInclude: "Employés inclus dans l'export :",
    onlySelected: (n) => `Uniquement les ${n} sélectionnés`,
    allEmployees: (n) => `Tous les employés (${n})`,
    colsHeader: (n) => `Colonnes à exporter (${n} sélectionnées)`,
    onlyNameCodePin: 'Uniquement nom, code & PIN',
    selAll: 'Tout sélectionner',
    deselect: 'Désélectionner',
    formatLabel: 'Format du fichier :',
    download: (fmt) => `Télécharger ${fmt}`,
    sheetName: 'Employés',
    statusActive: 'Actif',
    statusArchived: 'Archivé',
    cols: {
      full_name: 'Nom et prénom',
      employee_code: "Code employé",
      pin_code: 'PIN de pointage',
      job_title: 'Poste / Rôle',
      cnp: 'CNP',
      birth_date: 'Date de naissance',
      phone: 'Numéro de téléphone',
      email: 'E-mail',
      address: 'Adresse du domicile',
      location_name: 'Lieu de travail / Site',
      work_schedule: 'Durée du travail',
      salary: 'Salaire',
      contract_start_date: 'Date de début du contrat',
      id_card_series: "Série et numéro de la carte d'identité",
      status: 'Statut (Actif / Archivé)'
    }
  },
  nl: {
    title: 'Werknemersteam',
    subtitle: 'Beheer het personeel dat op deze locatie mag scannen.',
    exportData: 'Gegevens exporteren',
    addEmployee: 'Werknemer toevoegen',
    loading: 'Werknemers laden...',
    tabActive: 'Actief',
    tabArchive: 'Archief',
    searchPh: 'Zoek op naam, code of CNP...',
    searchArchivePh: 'Zoeken in archief...',
    results: 'res.',
    selOne: 'werknemer geselecteerd',
    selMany: 'werknemers geselecteerd',
    helpArchived: 'Je kunt de geselecteerde werknemers terugzetten naar de actieve lijst.',
    helpActive: 'Je kunt de functie/locatie in bulk wijzigen of de geselecteerde records archiveren.',
    exportBtn: 'Exporteren',
    restore: 'Herstellen',
    editData: 'Gegevens bewerken',
    bulkEdit: 'Bulk bewerken',
    archive: 'Archiveren',
    cancel: 'Annuleren',
    pageSelPre: 'Alle',
    pageSelPost: 'werknemers op deze pagina zijn geselecteerd.',
    selectAllFiltered: (n) => `Selecteer alle ${n} werknemers in de gefilterde lijst`,
    tipDeselectAll: 'Alles deselecteren',
    tipSelectAllPage: 'Alles op deze pagina selecteren',
    thNr: 'Nr.',
    thEmployee: 'Werknemer',
    thJob: 'Functie',
    thBirth: 'Geboortedatum / Leeftijd',
    thPin: 'Pincode / Toegang',
    thActions: 'Acties',
    noRecords: 'Geen records gevonden.',
    addFirst: 'Voeg de eerste werknemer toe',
    pinResetBadge: 'Pincode-reset aangevraagd',
    unknownLoc: 'Onbekende werkplek',
    years: (n) => `${n} jaar`,
    tipRestoreArchive: 'Herstellen uit archief',
    tipResetPin: 'Pincode resetten',
    tipPrint: 'Badge afdrukken (QR)',
    tipEdit: 'Werknemer bewerken',
    tipArchive: 'Werknemer archiveren',
    show: 'Toon',
    all: 'Alle',
    totalRecords: 'Totaal records:',
    pageOf: (p, n) => `Pagina ${p} van ${n}`,
    archiveTitle: 'Werknemer archiveren',
    archiveMsg: (name) => `Weet je zeker dat je ${name} wilt archiveren? De werknemer wordt naar het archief verplaatst, kan niet meer registreren en de code blijft gereserveerd om conflicten te voorkomen.`,
    restoreTitle: 'Werknemer herstellen',
    restoreMsg: (name) => `Weet je zeker dat je ${name} uit het archief wilt reactiveren? De werknemer kan weer registreren met dezelfde code.`,
    bulkArchiveTitle: 'Bulk archiveren',
    bulkArchiveMsg: (n) => `Weet je zeker dat je de ${n} geselecteerde werknemers wilt archiveren? Ze worden naar het archief verplaatst en hun codes blijven gereserveerd.`,
    archiving: 'Archiveren...',
    archiveN: (n) => `Archiveren (${n})`,
    bulkRestoreTitle: 'Bulk herstellen',
    bulkRestoreMsg: (n) => `Weet je zeker dat je de ${n} geselecteerde werknemers uit het archief wilt reactiveren?`,
    restoring: 'Herstellen...',
    restoreN: (n) => `Herstellen (${n})`,
    bulkModalTitle: 'Werknemers in bulk bewerken',
    bulkSubPre: 'Pas wijzigingen tegelijk toe op de',
    bulkSubPost: 'geselecteerde werknemers',
    bulkChangeJob: 'Functie (rol) wijzigen',
    bulkNoJob: '-- Geen functie toegewezen --',
    bulkChangeLoc: 'Werkplek (locatie) wijzigen',
    bulkNoLoc: '-- Geen werkplek toegewezen --',
    applying: 'Toepassen...',
    applyTo: (n) => `Toepassen op ${n} ${n === 1 ? 'werknemer' : 'werknemers'}`,
    resetPinTitle: 'Pincode resetten',
    resetPinMsgShort: 'Weet je zeker dat je de pincode van deze werknemer wilt resetten?',
    resetPinMsgLong: 'Weet je zeker dat je de pincode van deze werknemer wilt resetten? De werknemer krijgt een nieuwe pincode.',
    resetBtn: 'Resetten',
    pinResetDone: 'Pincode gereset',
    pinResetOk: (pin) => `De pincode is succesvol gereset!\nDe nieuwe pincode is: ${pin}`,
    success: 'Gelukt',
    close: 'Sluiten',
    defaultJob: 'Werknemer',
    qrScanNote: 'Het scannen gebeurt met de kiosktablet of een ander apparaat.',
    qrSendLink: 'Stuur de portallink naar de werknemer zodat deze kan inloggen en de digitale badge kan openen.',
    copied: 'Gekopieerd!',
    copyLink: 'Portallink kopiëren',
    modalEdit: 'Werknemer bewerken',
    modalAdd: 'Nieuwe werknemer toevoegen',
    modalEditSub: 'Werknemersgegevens bijwerken',
    modalAddSub: 'Registratieprofiel en identificatiegegevens',
    tab1: '1. Gegevens & Contact',
    tab2: '2. Functie & Contract',
    increaseSeats: 'Abonnementsplaatsen vergroten (prorata)',
    ocrBusy: 'Automatisch scannen bezig...',
    ocrIdle: 'Klik hier om een identiteitskaart te scannen',
    ocrHint: 'Het systeem knipt en haalt de foto van de werknemer automatisch uit de kaart.',
    avatarAlt: 'Uitgelezen avatar',
    avatarCaption: 'Foto automatisch uitgelezen',
    lastName: 'Achternaam *',
    firstName: 'Voornaam *',
    cnp: 'CNP *',
    birthDate: 'Geboortedatum',
    extractedFrom: 'Uit CNP / identiteitskaart',
    idSeries: 'Serie en nummer identiteitskaart',
    address: 'Adres (van identiteitskaart)',
    phone: 'Telefoon',
    email: 'E-mail',
    jobLabel: 'Beroep (functie in het bedrijf)',
    chooseJob: '-- Kies een beroep --',
    newBtn: 'Nieuw',
    newJobPh: 'Naam nieuw beroep...',
    pinLabel: 'Toegangspincode (uit CNP)',
    pinHelp: 'Deze pincode (kort wachtwoord) komt uit de laatste 4 cijfers van het CNP. De werknemer gebruikt hem alleen om de QR-code op de tablet te scannen bij het in-/uitklokken.',
    workSite: 'Werkplek',
    noFixedSite: '-- Geen vaste werkplek --',
    hireDate: 'Datum indiensttreding',
    salary: 'Salaris',
    salaryPh: 'Bijv.: 4000 RON',
    contractNotes: 'Contractnotities',
    notesPh: 'Aanvullende details...',
    saveEmployee: 'Werknemer opslaan',
    errOcr: 'Fout bij het lezen van de identiteitskaart. Vul handmatig in.',
    errSave: 'Fout bij het opslaan. Controleer de gegevens.',
    errBulkArchive: 'Fout bij het in bulk archiveren van de werknemers.',
    errBulkRestore: 'Fout bij het in bulk herstellen van de werknemers.',
    errBulkUpdate: 'Fout bij de bulkupdate.',
    errBulkPick: 'Vink minstens één veld aan om te wijzigen (functie of werkplek).',
    errConn: 'Fout bij de verbinding met de server.',
    errConn2: 'Verbindingsfout met de server.',
    alertNoEmp: 'Er zijn geen werknemers om te exporteren.',
    alertNoCol: 'Selecteer minstens één kolom om te exporteren.',
    exportModalTitle: 'Werknemersgegevens exporteren',
    exportModalSub: 'Selecteer de kolommen en het gewenste formaat voor het downloaden.',
    exportInclude: 'Werknemers opgenomen in de export:',
    onlySelected: (n) => `Alleen de ${n} geselecteerde`,
    allEmployees: (n) => `Alle werknemers (${n})`,
    colsHeader: (n) => `Te exporteren kolommen (${n} geselecteerd)`,
    onlyNameCodePin: 'Alleen naam, code & pincode',
    selAll: 'Alles selecteren',
    deselect: 'Deselecteren',
    formatLabel: 'Bestandsformaat:',
    download: (fmt) => `${fmt} downloaden`,
    sheetName: 'Werknemers',
    statusActive: 'Actief',
    statusArchived: 'Gearchiveerd',
    cols: {
      full_name: 'Volledige naam',
      employee_code: 'Werknemerscode',
      pin_code: 'Registratiepincode',
      job_title: 'Functie / Rol',
      cnp: 'CNP',
      birth_date: 'Geboortedatum',
      phone: 'Telefoonnummer',
      email: 'E-mail',
      address: 'Woonadres',
      location_name: 'Werkplek / Locatie',
      work_schedule: 'Werkrooster',
      salary: 'Salaris',
      contract_start_date: 'Startdatum contract',
      id_card_series: 'Serie en nummer identiteitskaart',
      status: 'Status (Actief / Gearchiveerd)'
    }
  }
};

const LOCALES = { ro: 'ro-RO', en: 'en-GB', fr: 'fr-FR', nl: 'nl-NL' };

export function getEmployeesLabels(language) {
  const lang = LABELS[language] ? language : 'ro';
  return { L: LABELS[lang], locale: LOCALES[lang] };
}
